version: '3.8'
services:
#  adonis_app:
#    container_name: adonis_app
#    build:
#      context: .
#    volumes:
#      - .:/home/node/app
#    ports: 
#      - 3333:3333
#    depends_on:
#      - database

#  adminer:
#      image: adminer:latest
#      restart: always
#      ports:
#        - 8080:8080
#      depends_on:
#        - database

  database:
    container_name: adonis_sql
    image: mysql:latest
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports: 
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_HOST: localhost
      MYSQL_DATABASE: adonis
      MYSQL_USER: adonis
      MYSQL_PASSWORD: adonis
      MYSQL_ROOT_PASSWORD: adonis
      MYSQL_TCP_PORT: 3306

    volumes:
      - ./database/docker/container_mysql:/var/lib/mysql
      
  